### ISSUE TITLE
Broken post-install on Node 8.1.1, working on Node 8.1.0

### ISSUE THREAD

**Issue by AlexTes** [sindresorhus/pwuid#4]
Il'l do some digging to see if this isn't a Node issue but I'm low on time, so quick heads-up 😉 .
Note the extra `/` in the URL.
```
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/alexander/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:120:20)
gyp ERR! stack     at Request.emit (events.js:210:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/alexander/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/request/request.js:1074:10)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
gyp ERR! stack     at emitOne (events.js:115:13)
```

**Comment by AlexTes** [comment]
See: https://github.com/nodejs/node/issues/13667
